'use client';

import React, { useState, useEffect } from 'react';
import {
  CheckCircle2,
  RefreshCw,
  Save,
  Download,
  Copy,
  Play,
  Terminal,
  Activity,
  ArrowRight,
  AlertCircle
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { useToast } from '@/components/ui/Toast';
import { validateYaml, saveAsYaml } from '@/actions/connection';
import { useRouter } from 'next/navigation';

export default function EditorPage() {
  const { showToast } = useToast();
  const router = useRouter();
  const [yaml, setYaml] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [isValidating, setIsValidating] = useState(false);
  const [validationErrors, setValidationErrors] = useState<string[]>([]);
  const [isValid, setIsValid] = useState<boolean | null>(null);

  // Load YAML from localStorage (saved by Studio after a successful run)
  useEffect(() => {
    const saved = localStorage.getItem('anchor_yaml');
    if (saved) {
      setYaml(saved);
    } else {
      setYaml('# No pipeline generated yet.\n# Go to Studio to generate one first.');
    }
  }, []);

  const lines = yaml.split('\n');

  const handleValidate = async () => {
    setIsValidating(true);
    const res = await validateYaml(yaml);
    setIsValidating(false);
    if (res.valid) {
      setIsValid(true);
      setValidationErrors([]);
      showToast('YAML is valid!', 'success');
    } else {
      setIsValid(false);
      setValidationErrors(res.errors || []);
      showToast(`${res.errors?.length || 1} issue(s) found`, 'error');
    }
  };

  const handleSaveAs = async () => {
    setIsSaving(true);
    const res = await saveAsYaml(yaml);
    setIsSaving(false);
    if (res.success) {
      showToast(res.message || 'Saved!', 'success');
    } else {
      showToast(res.error || 'Save cancelled', 'error');
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(yaml);
    showToast('YAML copied to clipboard', 'success');
  };

  const handleDownload = () => {
    const blob = new Blob([yaml], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'anchor.yml';
    a.click();
    showToast('Downloading anchor.yml...', 'success');
  };

  return (
    <div className="flex flex-col h-screen overflow-hidden bg-[#0E0E11]">

      {/* Top banner */}
      {isValid === true && (
        <div className="bg-green-500/10 border-b border-green-500/20 py-2 px-8 flex items-center gap-3">
          <CheckCircle2 size={16} className="text-green-500" />
          <span className="text-xs font-medium text-green-400">YAML validated — no issues found.</span>
        </div>
      )}
      {isValid === false && (
        <div className="bg-red-500/10 border-b border-red-500/20 py-2 px-8 flex items-center gap-3">
          <AlertCircle size={16} className="text-red-500" />
          <span className="text-xs font-medium text-red-400">{validationErrors.length} issue(s) found — see panel below.</span>
        </div>
      )}

      {/* Header */}
      <div className="p-6 border-b border-gray-800/50 flex justify-between items-center">
        <div>
          <h2 className="text-xl font-bold text-white tracking-tight">YAML Editor</h2>
          <p className="text-xs text-gray-500 mt-1">Viewing the pipeline generated by Studio. Edit freely.</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleValidate}
            disabled={isValidating}
            className="flex items-center gap-2 px-4 py-2 bg-gray-800 border border-gray-700 rounded-md text-sm text-gray-300 hover:bg-gray-700 transition"
          >
            {isValidating ? <RefreshCw size={14} className="animate-spin" /> : <Activity size={14} />}
            Validate
          </button>
          <button
            onClick={() => router.push('/studio')}
            className="flex items-center gap-2 px-4 py-2 bg-gray-800 border border-gray-700 rounded-md text-sm text-gray-300 hover:bg-gray-700 transition"
          >
            <Play size={14} /> Re-run Studio
          </button>
        </div>
      </div>

      {/* Split pane */}
      <div className="flex-1 flex overflow-hidden">

        {/* Left: editable YAML */}
        <div className="flex-1 flex flex-col border-r border-gray-800/50 bg-[#0A0A0D]">
          <div className="p-3 border-b border-gray-800/50 flex justify-between items-center bg-gray-900/30">
            <div className="flex items-center gap-2 text-xs font-bold text-gray-400 uppercase tracking-widest">
              <Terminal size={14} className="text-brand-primary" /> anchor.yml
            </div>
            <span className="text-[10px] text-gray-600 font-mono">{lines.length} lines</span>
          </div>
          <div className="flex-1 overflow-auto flex font-mono text-xs leading-relaxed">
            {/* Line numbers */}
            <div className="p-4 pr-3 text-gray-700 text-right select-none border-r border-gray-800/50 bg-black/20 min-w-[48px]">
              {lines.map((_, i) => <div key={i}>{i + 1}</div>)}
            </div>
            {/* Editable area */}
            <textarea
              value={yaml}
              onChange={e => { setYaml(e.target.value); setIsValid(null); }}
              className="flex-1 p-4 bg-transparent text-gray-300 outline-none resize-none font-mono text-xs leading-relaxed"
              spellCheck={false}
            />
          </div>
        </div>

        {/* Right: validation errors / info panel */}
        <div className="w-[360px] flex flex-col bg-[#0D0D10]">
          <div className="p-3 border-b border-gray-800/50 bg-gray-900/30 flex items-center gap-2 text-xs font-bold text-gray-400 uppercase tracking-widest">
            <Activity size={14} className="text-yellow-500" /> Analysis
          </div>
          <div className="flex-1 overflow-auto p-6 space-y-4">
            {validationErrors.length > 0 ? (
              <>
                <p className="text-xs font-bold text-red-400 uppercase tracking-wider">Issues ({validationErrors.length})</p>
                {validationErrors.map((err, i) => (
                  <div key={i} className="p-3 bg-red-950/30 border border-red-900/40 rounded-lg flex items-start gap-2">
                    <AlertCircle size={14} className="text-red-500 mt-0.5 flex-shrink-0" />
                    <p className="text-xs text-red-300">{err}</p>
                  </div>
                ))}
              </>
            ) : isValid === true ? (
              <div className="flex flex-col items-center justify-center h-full text-center space-y-3">
                <CheckCircle2 size={40} className="text-green-500" />
                <p className="text-sm font-bold text-white">All checks passed</p>
                <p className="text-xs text-gray-500">Your pipeline is clean and ready for deployment.</p>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center h-full text-center space-y-3 opacity-30">
                <Activity size={40} />
                <p className="text-sm">Click Validate to check your YAML</p>
              </div>
            )}
          </div>
        </div>

      </div>

      {/* Footer */}
      <div className="p-4 border-t border-gray-800/50 bg-[#0E0E11] flex justify-between items-center">
        <div className="flex gap-2">
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-4 py-2 bg-gray-800/50 border border-gray-800 rounded-md text-sm text-gray-400 hover:text-gray-200 transition"
          >
            <Download size={14} /> Download
          </button>
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 bg-gray-800/50 border border-gray-800 rounded-md text-sm text-gray-400 hover:text-gray-200 transition"
          >
            <Copy size={14} /> Copy
          </button>
        </div>
        <button
          onClick={handleSaveAs}
          disabled={isSaving}
          className="flex items-center gap-2 px-8 py-2 rounded bg-brand-primary text-black text-sm font-bold hover:bg-brand-primary/90 transition shadow-lg shadow-brand-primary/20"
        >
          {isSaving ? <RefreshCw size={14} className="animate-spin" /> : <Save size={14} />}
          Save As... <ArrowRight size={14} />
        </button>
      </div>

    </div>
  );
}
