package generator

import (
	"strings"

	"github.com/fusiontech/yaml-anchor/pkg/analyzer"
	"gopkg.in/yaml.v3"
)

// GitHub Action YAML Structs
type Workflow struct {
	Name string         `yaml:"name"`
	On   map[string]any `yaml:"on"`
	Jobs map[string]Job `yaml:"jobs"`
}

type Job struct {
	RunsOn string   `yaml:"runs-on,omitempty"`
	Needs  []string `yaml:"needs,omitempty"`
	Steps  []Step   `yaml:"steps,omitempty"`
}

type Step struct {
	Name string `yaml:"name,omitempty"`
	Uses string `yaml:"uses,omitempty"`
	Run  string `yaml:"run,omitempty"`
}

// GitLab CI Structs
type GitlabCI struct {
	Stages []string                `yaml:"stages"`
	Jobs   map[string]GitlabCIJob `yaml:",inline"`
}

type GitlabCIJob struct {
	Stage  string   `yaml:"stage"`
	Image  string   `yaml:"image,omitempty"`
	Script []string `yaml:"script"`
}

// GenerateYAML converts the code analysis into a CI/CD YAML string.
func GenerateYAML(analysis *analyzer.CodeAnalysis, provider string) (string, error) {
	if provider == "gitlab" {
		return generateGitlabCI(analysis)
	}
	return generateGithubActions(analysis)
}

func generateGithubActions(analysis *analyzer.CodeAnalysis) (string, error) {
	workflow := Workflow{
		Name: "YamlAnchor CI",
		On: map[string]any{
			"push": map[string]any{
				"branches": []string{"main"},
			},
			"pull_request": map[string]any{
				"branches": []string{"main"},
			},
		},
		Jobs: make(map[string]Job),
	}

	testSteps := []Step{
		{Uses: "actions/checkout@v4"},
	}

	if strings.Contains(analysis.Language, "Go") {
		testSteps = append(testSteps, Step{Uses: "actions/setup-go@v5"})
		testSteps = append(testSteps, Step{Name: "Run Go Tests", Run: "go test ./..."})
	}
	if strings.Contains(analysis.Language, "Node.js") {
		testSteps = append(testSteps, Step{Uses: "actions/setup-node@v4"})
		testSteps = append(testSteps, Step{Name: "Install Node Dependencies", Run: "npm ci"})
		testSteps = append(testSteps, Step{Name: "Run Node Tests", Run: "npm test"})
	}
	if strings.Contains(analysis.Language, "Python") {
		testSteps = append(testSteps, Step{Uses: "actions/setup-python@v4"})
		testSteps = append(testSteps, Step{Name: "Install Python Dependencies", Run: "pip install -r requirements.txt"})
		testSteps = append(testSteps, Step{Name: "Run Python Tests", Run: "pytest"})
	}

	workflow.Jobs["test"] = Job{
		RunsOn: "ubuntu-latest",
		Steps:  testSteps,
	}

	lastJob := "test"

	if analysis.Dockerfile {
		workflow.Jobs["build"] = Job{
			RunsOn: "ubuntu-latest",
			Needs:  []string{"test"},
			Steps: []Step{
				{Uses: "actions/checkout@v4"},
				{Name: "Build Docker Image", Run: "docker build -t yaml-anchor-app ."},
			},
		}
		lastJob = "build"
	}

	workflow.Jobs["deploy"] = Job{
		RunsOn: "ubuntu-latest",
		Needs:  []string{lastJob},
		Steps: []Step{
			{Name: "Deploy Application", Run: "echo 'Deploying application...'"},
		},
	}

	yamlData, err := yaml.Marshal(&workflow)
	if err != nil {
		return "", err
	}

	return "# Auto-generated by YamlAnchor\n# Tech Stack Detected: " + analysis.Language + "\n\n" + string(yamlData), nil
}

func generateGitlabCI(analysis *analyzer.CodeAnalysis) (string, error) {
	ci := GitlabCI{
		Stages: []string{"test", "build", "deploy"},
		Jobs:   make(map[string]GitlabCIJob),
	}

	testScript := []string{}
	if strings.Contains(analysis.Language, "Go") {
		testScript = append(testScript, "go test ./...")
	}
	if strings.Contains(analysis.Language, "Node.js") {
		testScript = append(testScript, "npm ci", "npm test")
	}
	if strings.Contains(analysis.Language, "Python") {
		testScript = append(testScript, "pip install -r requirements.txt", "pytest")
	}

	ci.Jobs["test_job"] = GitlabCIJob{
		Stage:  "test",
		Image:  "ubuntu:latest",
		Script: testScript,
	}

	if analysis.Dockerfile {
		ci.Jobs["build_job"] = GitlabCIJob{
			Stage:  "build",
			Image:  "docker:latest",
			Script: []string{"docker build -t yaml-anchor-app ."},
		}
	}

	ci.Jobs["deploy_job"] = GitlabCIJob{
		Stage:  "deploy",
		Image:  "ubuntu:latest",
		Script: []string{"echo 'Deploying application...'"},
	}

	yamlData, err := yaml.Marshal(&ci)
	if err != nil {
		return "", err
	}

	// Workaround for inline map in Go YAML to root keys
	// We marshal the wrapper but we really want the map at root. 
	// For simplicity, we can construct the map manually or clean it.
	return "# Auto-generated GitLab CI by YamlAnchor\n# Tech Stack Detected: " + analysis.Language + "\n\n" + string(yamlData), nil
}
